# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

repository: sungheeyun/sungheeyun.github.io

title: Sunghee's Homepage
email: sunghee.yun@gmail.com
description: I am Sunghee Yun.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: US/Pacific # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name             : "Sunghee Yun (He/Him)"
  avatar           : "/assets/images/profile-photo-670x671.png"
  bio              : 'Co-Founder &amp; CTO @ [Erudio Bio, Inc.](https://sungheeyun-erudio.github.io/){:target="_blank"},
  Co-Founder &amp; CEO @ Erudio Bio Korea, Inc.,
  Leader of [Silicon Valley Privacy Preserving AI Forum (K-PAI)](https://k-privateai.github.io/){:target="_blank"},
  CGO / Global Managing Partner @ [LULUMEDIC](https://www.lulumedic.com/en/){:target="_blank"},
  [KFAS-Salzburg Global Leadership Initiative Fellow](https://www.salzburgglobal.org/newsroom/latest-news/introducing-the-second-cohort-of-the-kfas-salzburg-global-leadership-initiative){:target="_blank"} @ [Salzburg Global Seminar](https://www.salzburgglobal.org/){:target="_blank"},
  AI-Korean Medicine Integration Initiative Task Force Member @ [The Association of Korean Medicine](https://www.akom.org/English/Index){:target="_blank"},
  Director of AI Semiconductor @ [K-BioX](https://kbiox.net/){:target="_blank"},
  Visiting Professor @ [Sogang University](https://ee.sogang.ac.kr/eng/employee/professor03.php){:target="_blank"},
  Advisory Professor @ [DGIST](https://www.dgist.ac.kr/en_eecs/?bo_table=eng2_1&sca=Advisory+Professor){:target="_blank"},
  Global Advisory Board Member @ [Innovative Future Brain-Inspired Intelligence System Semiconductor of Sogang University](https://bk4semicon.sogang.ac.kr/kor/about/org.php){:target="_blank"},
  Network Expert @ [Gerson Lehrman Group](https://glginsights.com/){:target="_blank"},
  Chief Business Development Officer @ [WeStory.ai](https://westory.ai/){:target="_blank"},
  and
  Advisor @ [CryptoLab, Inc.](https://www.cryptolab.co.kr/en/home/){:target="_blank"}'
#  location         : "Palo Alto, CA, USA"
#  email            : sunghee.yun@gmail.com
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/sungheeyun/sungheeyun.github.io"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/sungheeyun/"
    - label: "Blog"
      icon: "fa-solid fa-blog"
      url: "https://sungheeyun.github.io"
    - label: "Mathematics Genealogy Project"
      icon: "fa-solid fa-infinity"
      url: "https://www.genealogy.math.ndsu.nodak.edu/id.php?id=283283"
    - label: "Erudio Bio, Inc."
      icon: "fa-solid fa-dna"
      url: "https://sungheeyun-erudio.github.io"
    - label: "CryptoLab, Inc."
      icon: "fa-solid fa-lock"
      url: "https://www.cryptolab.co.kr/en/home/"
    - label: "K-PAI"
      icon: "fa-solid fa-chart-pie"
      url: "https://k-privateai.github.io/"
    - label: "Salzburg Global Leadership Initiative"
      icon: "fa-solid fa-globe"
      url: "https://www.salzburgglobal.org/multi-year-series/kfas/pageId/11076"
    - label: "Solar"
      icon: "fa-solid fa-sun"
      url: "https://solar-society.github.io"
    - label: "Wet Lab, Novato, CA, USA"
      icon: "fa-solid fa-flask-vial"
      url: "https://maps.app.goo.gl/Am64VJtCjxss6Vgz8"
    - label: "KIC, San Jose, CA, USA"
      icon: "fa-solid fa-building"
      url: "https://maps.app.goo.gl/EQR3rsKcMmDqNELH6"
    - label: "Jeonbuk Tech Biz Center, South Korea"
      icon: "fa-solid fa-building"
      url: "https://naver.me/FLyt9xfR"
    - label: "D.N., Seoul, South Korea"
      icon: "fa-regular fa-building"
      url: "https://naver.me/GPrFr8UZ"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:sunghee.yun@gmail.com"
    - label: "CV"
      icon: "fa-solid fa-file"
      url: "/resource/CV/Sunghee_Yun_CV_2.pdf"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=KSZEwgIAAAAJ"
    - label: "ACM"
      icon: "fa-solid fa-robot"
      url: "https://dl.acm.org/profile/81332537295"
    - label: "ResearchGate"
      icon: "fa-brands fa-researchgate"
      url: "https://www.researchgate.net/profile/Sunghee-Yun"
    - label: "dblp"
      icon: "fa-solid fa-circle-user"
      url: "https://dblp.org/pid/06/3258.html"
    - label: "orcid"
      icon: "fa-brands fa-orcid"
      url: "https://dblp.org/pid/06/3258.html"
    - label: "stack overflow"
      icon: "fa-brands fa-stack-overflow"
      url: "https://stackoverflow.com/users/1973237/sunghee-yun"
    - label: "Facebook"
      icon: "fa-brands fa-facebook"
      url: "https://facebook.com/sunghee.yun1"
    - label: "YouTube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@SungheeYun"
    - label: "Pinterest"
      icon: "fa-brands fa-pinterest"
      url: "https://kr.pinterest.com/sunghee14/"
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/sunghee.yun/"
    - label: "Twitter"
      icon: "fa-brands fa-square-x-twitter"
      url: "https://twitter.com/sunghee14"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/sungheeyun/sungheeyun.github.io"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/sungheeyun/"
    - label: "Blog"
      icon: "fa-solid fa-blog"
      url: "https://sungheeyun.github.io"
    - label: "Mathematics Genealogy Project"
      icon: "fa-solid fa-infinity"
      url: "https://www.genealogy.math.ndsu.nodak.edu/id.php?id=283283"
    - label: "Erudio Bio, Inc."
      icon: "fa-solid fa-dna"
      url: "https://sungheeyun-erudio.github.io"
    - label: "CryptoLab, Inc."
      icon: "fa-solid fa-lock"
      url: "https://www.cryptolab.co.kr/en/home/"
    - label: "K-PAI"
      icon: "fa-solid fa-chart-pie"
      url: "https://k-privateai.github.io/"
    - label: "Salzburg Global Leadership Initiative"
      icon: "fa-solid fa-globe"
      url: "https://www.salzburgglobal.org/multi-year-series/kfas/pageId/11076"
    - label: "Solar"
      icon: "fa-solid fa-sun"
      url: "https://solar-society.github.io"
    - label: "Wet Lab, Novato, CA, USA"
      icon: "fa-solid fa-flask-vial"
      url: "https://maps.app.goo.gl/Am64VJtCjxss6Vgz8"
    - label: "KIC, San Jose, CA, USA"
      icon: "fa-solid fa-building"
      url: "https://maps.app.goo.gl/EQR3rsKcMmDqNELH6"
    - label: "Jeonbuk Tech Biz Center, South Korea"
      icon: "fa-solid fa-building"
      url: "https://naver.me/FLyt9xfR"
    - label: "D.N., Seoul, South Korea"
      icon: "fa-regular fa-building"
      url: "https://naver.me/GPrFr8UZ"
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:sunghee.yun@gmail.com"
    - label: "CV"
      icon: "fa-solid fa-file"
      url: "/resource/CV/Sunghee_Yun_CV_2.pdf"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=KSZEwgIAAAAJ"
    - label: "ACM"
      icon: "fa-solid fa-robot"
      url: "https://dl.acm.org/profile/81332537295"
    - label: "ResearchGate"
      icon: "fa-brands fa-researchgate"
      url: "https://www.researchgate.net/profile/Sunghee-Yun"
    - label: "dblp"
      icon: "fa-solid fa-circle-user"
      url: "https://dblp.org/pid/06/3258.html"
    - label: "orcid"
      icon: "fa-brands fa-orcid"
      url: "https://dblp.org/pid/06/3258.html"
    - label: "stack overflow"
      icon: "fa-brands fa-stack-overflow"
      url: "https://stackoverflow.com/users/1973237/sunghee-yun"
    - label: "Facebook"
      icon: "fa-brands fa-facebook"
      url: "https://facebook.com/sunghee.yun1"
    - label: "YouTube"
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@SungheeYun"
    - label: "Pinterest"
      icon: "fa-brands fa-pinterest"
      url: "https://kr.pinterest.com/sunghee14/"
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/sunghee.yun/"
    - label: "Twitter"
      icon: "fa-brands fa-square-x-twitter"
      url: "https://twitter.com/sunghee14"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      #classes: wide
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      #classes: wide
      layout: single
      author_profile: true

category:
  type: liquid
  path: /categories/
tag:
  type: liquid
  path: /tags/
